<a href="https://colab.research.google.com/github/akanksha1022/Dashboard-in-Excel/blob/main/Data_analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_list =[1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[5,6,7],[3,9,7]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [5, 6, 7],
       [3, 9, 7]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.54969168, 0.22285883, 0.2280027 , 0.4645206 , 0.51542306])

In [18]:
np.random.rand(8)

array([0.48279776, 0.50306213, 0.6110104 , 0.57028641, 0.98188752,
       0.48579748, 0.54021975, 0.17514429])

In [19]:
np.random.rand(5,5)

array([[0.11347199, 0.22445608, 0.63595245, 0.88527519, 0.98601437],
       [0.2762801 , 0.4965515 , 0.97827946, 0.21983633, 0.6735836 ],
       [0.93021195, 0.10810565, 0.9323865 , 0.40993604, 0.1391537 ],
       [0.18207588, 0.62124566, 0.89464306, 0.51832833, 0.17288573],
       [0.89781355, 0.26364275, 0.79623723, 0.22551053, 0.94721089]])

In [21]:
np.random.randint(1,60)

58

In [22]:
np.random.randint(1,100,45)

array([12, 62,  8, 25, 44, 29, 96, 44, 36, 41, 98,  3, 11, 60, 42, 51, 95,
       33, 45,  3, 37, 98, 30, 41,  4, 24, 30, 81, 62, 68, 38, 93, 70, 76,
        7, 72, 28,  1, 40, 36, 16,  4, 44, 74, 94])

In [23]:
poxy = np.random.randint(0,50,15)

In [24]:
poxy

array([29,  6, 26, 21, 40,  2, 43, 39,  0, 30, 18,  8, 16, 26, 46])

In [26]:
from numpy.random import randint

In [30]:
randint(2,10)

6

In [38]:
arr.shape

(3,)

In [39]:
arr.dtype

dtype('int64')

In [48]:
ranarr = [[45,23,89,43,67,23,77,45,32]]

In [49]:
ranarr

[[45, 23, 89, 43, 67, 23, 77, 45, 32]]

In [51]:
ar=np.arange(4,50,6)

In [52]:
arr

array([1, 2, 3])

In [53]:
arr[0:7]

array([1, 2, 3])

In [54]:
arr[0:3]

array([1, 2, 3])

In [55]:
arr[1:6]

array([2, 3])

In [56]:
arr[5:]

array([], dtype=int64)

In [59]:
arr[0:5] =100

In [60]:
arr

array([100, 100, 100])

In [61]:
slice_of_arr =arr[0:6]

In [62]:
slice_of_arr

array([100, 100, 100])

In [63]:
slice_of_arr[:]

array([100, 100, 100])

In [64]:
arr

array([100, 100, 100])

In [65]:
slice_of_arr =arr[0:6]

In [66]:
slice_of_arr

array([100, 100, 100])

In [67]:
slice_of_arr[:] =99

In [68]:
slice_of_arr

array([99, 99, 99])

In [69]:
arr

array([99, 99, 99])

In [70]:
arr_copy = arr.copy()

In [71]:
arr

array([99, 99, 99])

In [72]:
arr_copy

array([99, 99, 99])

In [73]:
arr

array([99, 99, 99])

In [75]:
arr_copy[:] =100

In [76]:
arr_copy

array([100, 100, 100])

In [77]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,35,40]])

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [79]:
arr_2d[0][0]

5

In [80]:
arr_2d[0]

array([ 5, 10, 15])

In [82]:
arr_2d[1,2]

30

In [83]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
arr=np.arange(1,11)

In [86]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
bool_arr=arr>5

In [91]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [93]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [94]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [95]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [96]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [97]:
import numpy as np

In [100]:
arr =np.arange(0,11)

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [105]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [106]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
arr / arr

<ipython-input-107-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [109]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [110]:
np.max(arr)

10

In [111]:
np.min(arr)

0

In [112]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [113]:
import numpy as np

In [114]:
array = np.zeros(10)

In [115]:
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [118]:
array1 = np.ones(10)
array1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
array2 = np.ones(10) *5

In [121]:
array2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [123]:
array = np.arange(10,51)

In [124]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [125]:
array = np.arange(10,51,2)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [128]:
form = np.arange(0,9).reshape(3,3)
print(form)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [129]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [132]:
np.random.rand()

0.6016920641656629

In [133]:
np.random.rand(25)


array([0.70443008, 0.04490609, 0.41140513, 0.74553144, 0.00630951,
       0.76069782, 0.8681518 , 0.74990585, 0.73871149, 0.50167594,
       0.96571808, 0.32675316, 0.98744283, 0.85720713, 0.60083203,
       0.56954241, 0.35344925, 0.17109658, 0.24433866, 0.88803938,
       0.53537463, 0.22533424, 0.21836563, 0.03044149, 0.45292468])

In [135]:
linear = np.linspace(0,1,20)
print(linear)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [138]:
mat = np.arange(1,37).reshape(6,6)

In [139]:
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])